name: Build Feature Branch
on:
  push:
    branches:
      - on_http_error

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    strategy:
      matrix:
        build_type: [Release, Debug]
    uses: ./.github/workflows/build.yml
    with:
      build_type: ${{ matrix.build_type }}
